jwt:
  secret: '[a-zA-Z0-9]./G7FXA(n?7ATp_t6q(dL<PgnVjU6pgi>X([h8Xs,zgLHda`0$8+gUld0UjYbCAX'

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userportal
    username: root
    password: Dekeg07.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hinernate:
        dialect: org.hibernate.dialect.MySQL8Dialect